version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - rabbitmq
      - postgres
    env_file:
      - ./env/api.env
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - ./env/kafka.env
    depends_on:
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - ./env/zookeeper.env
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./env/rabbitmq.env
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: